import { useState, useEffect } from 'react';
import { DEFAULT_GENERATOR_SETTINGS } from './useSectorGenerator';

export function useSession() {
  const [initialSession] = useState(() => {
    if (typeof window === 'undefined') return null;
    try {
      const saved = localStorage.getItem('ssg_session');
      return saved ? JSON.parse(saved) : null;
    } catch (error) {
      console.error('Failed to load session', error);
      return null;
    }
  });

  const [gridSize, setGridSize] = useState(initialSession?.gridSize || { width: 8, height: 10 });
  const [generatorSettings, setGeneratorSettings] = useState(() => {
    const saved = initialSession?.generatorSettings || {};
    return {
      ...DEFAULT_GENERATOR_SETTINGS,
      ...saved,
      pendingGridSize: {
        ...DEFAULT_GENERATOR_SETTINGS.pendingGridSize,
        ...(saved.pendingGridSize || initialSession?.gridSize || {})
      },
      rangeLimits: {
        ...DEFAULT_GENERATOR_SETTINGS.rangeLimits,
        ...(saved.rangeLimits || {})
      }
    };
  });
  const [systems, setSystems] = useState(initialSession?.systems || {});
  const [showLeftSidebar, setShowLeftSidebar] = useState(initialSession?.showLeftSidebar ?? true);
  const [showRightSidebar, setShowRightSidebar] = useState(initialSession?.showRightSidebar ?? true);
  const [viewState, setViewState] = useState(initialSession?.viewState || { scale: 1, x: 0, y: 0 });
  
  const [autoGenerateOnMount, setAutoGenerateOnMount] = useState(() => {
    if (typeof window === 'undefined') return true;
    if (initialSession?.systems && Object.keys(initialSession.systems).length > 0) return false;
    return window.sessionStorage.getItem('ssg_auto_generated') !== '1';
  });

  const markAutoGenerated = () => {
    if (typeof window !== 'undefined') {
      window.sessionStorage.setItem('ssg_auto_generated', '1');
      setAutoGenerateOnMount(false);
    }
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      const session = {
        gridSize,
        systems,
        generatorSettings,
        showLeftSidebar,
        showRightSidebar,
        viewState
      };
      localStorage.setItem('ssg_session', JSON.stringify(session));
    }, 500);

    return () => clearTimeout(timer);
  }, [gridSize, systems, generatorSettings, showLeftSidebar, showRightSidebar, viewState]);

  return {
    gridSize, setGridSize,
    generatorSettings, setGeneratorSettings,
    systems, setSystems,
    showLeftSidebar, setShowLeftSidebar,
    showRightSidebar, setShowRightSidebar,
    viewState, setViewState,
    autoGenerateOnMount, markAutoGenerated
  };
}
