import React, { useState, useCallback, useMemo } from 'react';
import { HEX_SIZE, HEX_HEIGHT, SIDEBAR_WIDTH } from './constants';
import GeneratorPanel from './components/GeneratorPanel';
import InspectorPanel from './components/InspectorPanel';
import StarMap from './components/StarMap';
import { postProcessSystems } from './generation/systemPostProcessing';
import { useSession } from './hooks/useSession';

export default function App() {
  const {
    gridSize, setGridSize,
    generatorSettings, setGeneratorSettings,
    systems, setSystems,
    showLeftSidebar, setShowLeftSidebar,
    showRightSidebar, setShowRightSidebar,
    viewState, setViewState,
    sectorCoords, setSectorCoords,
    autoGenerateOnMount, markAutoGenerated
  } = useSession();

  const [selectedCoords, setSelectedCoords] = useState(null);
  const [focusedObject, setFocusedObject] = useState(null);

  const handleCoordsChange = useCallback((coords) => {
    setSelectedCoords(coords);
    setFocusedObject(null);
  }, []);

  const handleJump = useCallback((direction) => {
    // direction is { q, r } relative offset, or absolute coords?
    // Let's assume it's the target coords for now.
    setSectorCoords(direction);
    // We need to ensure the generator picks this up.
    setGeneratorSettings(prev => ({ ...prev, sectorCoords: direction }));
  }, [setSectorCoords, setGeneratorSettings]);

  const resetView = useCallback(
    (size = gridSize) => {
      // Center relative to entire viewport to prevent shifting when panels toggle
      const centerX = window.innerWidth / 2;
      const centerY = window.innerHeight / 2;
      const gridPixelWidth = size.width * 1.5 * HEX_SIZE;
      const gridPixelHeight = size.height * HEX_HEIGHT;

      setViewState({
        scale: 1,
        x: centerX - gridPixelWidth / 2,
        y: centerY - gridPixelHeight / 2
      });
    },
    [gridSize, setViewState]
  );

  const handleSectorGenerated = useCallback(
    (newSystems, newGridSize) => {
      const processedSystems = postProcessSystems(newSystems);

      setSystems(processedSystems);
      setGridSize(newGridSize);
      setSelectedCoords(null);
      resetView(newGridSize);

      if (autoGenerateOnMount) {
        markAutoGenerated();
      }
    },
    [autoGenerateOnMount, resetView, setSystems, setGridSize, markAutoGenerated]
  );

  const handleImport = useCallback((data) => {
    setSystems(data.systems);
    setGridSize(data.gridSize);
    if (data.generatorSettings) {
      setGeneratorSettings(data.generatorSettings);
    }
    setSelectedCoords(null);
    resetView(data.gridSize);
  }, [setSystems, setGridSize, setGeneratorSettings, resetView]);

  const generatorStyle = useMemo(() => ({ 
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    zIndex: 30,
    transform: showLeftSidebar ? 'translateX(0)' : 'translateX(-100%)',
    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  }), [showLeftSidebar]);

  const inspectorStyle = useMemo(() => ({
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 30,
    transform: showRightSidebar ? 'translateX(0)' : 'translateX(100%)',
    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  }), [showRightSidebar]);

  return (
    <div className="relative flex h-screen bg-slate-950 text-slate-100 font-sans overflow-hidden">
      <StarMap
        gridSize={gridSize}
        systems={systems}
        selectedCoords={selectedCoords}
        setSelectedCoords={handleCoordsChange}
        viewState={viewState}
        setViewState={setViewState}
        showLeftSidebar={showLeftSidebar}
        setShowLeftSidebar={setShowLeftSidebar}
        showRightSidebar={showRightSidebar}
        setShowRightSidebar={setShowRightSidebar}
        sectorCoords={sectorCoords}
        onNavigate={handleJump}
      />

      <GeneratorPanel
        onGenerate={handleSectorGenerated}
        style={generatorStyle}
        autoGenerateOnMount={autoGenerateOnMount}
        initialSettings={{ ...generatorSettings, sectorCoords }}
        onSettingsChange={setGeneratorSettings}
        systems={systems}
        gridSize={gridSize}
        onImport={handleImport}
      />

      <InspectorPanel
        gridSize={gridSize}
        systems={systems}
        sectorCoords={sectorCoords}
        selectedCoords={selectedCoords}
        setSelectedCoords={handleCoordsChange}
        focusedObject={focusedObject}
        setFocusedObject={setFocusedObject}
        onJump={handleJump}
        style={inspectorStyle}
      />
    </div>
  );
}

