import React, { useState, useCallback, useMemo } from 'react';
import { HEX_SIZE, HEX_HEIGHT, SIDEBAR_WIDTH } from './constants';
import GeneratorPanel from './components/GeneratorPanel';
import InspectorPanel from './components/InspectorPanel';
import StarMap from './components/StarMap';
import { postProcessSystems } from './generation/systemPostProcessing';
import { useSession } from './hooks/useSession';

export default function App() {
  const {
    gridSize, setGridSize,
    generatorSettings, setGeneratorSettings,
    systems, setSystems,
    showLeftSidebar, setShowLeftSidebar,
    showRightSidebar, setShowRightSidebar,
    viewState, setViewState,
    autoGenerateOnMount, markAutoGenerated
  } = useSession();

  const [selectedCoords, setSelectedCoords] = useState(null);
  const [focusedObject, setFocusedObject] = useState(null);

  const handleCoordsChange = useCallback((coords) => {
    setSelectedCoords(coords);
    setFocusedObject(null);
  }, []);

  const resetView = useCallback(
    (size = gridSize) => {
      const sidebarWidth = (showLeftSidebar ? SIDEBAR_WIDTH : 0) + (showRightSidebar ? SIDEBAR_WIDTH : 0);
      const centerX = (window.innerWidth - sidebarWidth) / 2;
      const centerY = window.innerHeight / 2;
      const gridPixelWidth = size.width * 1.5 * HEX_SIZE;
      const gridPixelHeight = size.height * HEX_HEIGHT;

      setViewState({
        scale: 1,
        x: centerX - gridPixelWidth / 2,
        y: centerY - gridPixelHeight / 2
      });
    },
    [gridSize, showLeftSidebar, showRightSidebar, setViewState]
  );

  const handleSectorGenerated = useCallback(
    (newSystems, newGridSize) => {
      const processedSystems = postProcessSystems(newSystems);

      setSystems(processedSystems);
      setGridSize(newGridSize);
      setSelectedCoords(null);
      resetView(newGridSize);

      if (autoGenerateOnMount) {
        markAutoGenerated();
      }
    },
    [autoGenerateOnMount, resetView, setSystems, setGridSize, markAutoGenerated]
  );

  const handleImport = useCallback((data) => {
    setSystems(data.systems);
    setGridSize(data.gridSize);
    if (data.generatorSettings) {
      setGeneratorSettings(data.generatorSettings);
    }
    setSelectedCoords(null);
    resetView(data.gridSize);
  }, [setSystems, setGridSize, setGeneratorSettings, resetView]);

  const generatorStyle = useMemo(() => ({ display: showLeftSidebar ? 'flex' : 'none' }), [showLeftSidebar]);

  return (
    <div className="flex h-screen bg-slate-950 text-slate-100 font-sans overflow-hidden">
      <GeneratorPanel
        onGenerate={handleSectorGenerated}
        style={generatorStyle}
        autoGenerateOnMount={autoGenerateOnMount}
        initialSettings={generatorSettings}
        onSettingsChange={setGeneratorSettings}
        systems={systems}
        gridSize={gridSize}
        onImport={handleImport}
      />

      <StarMap
        gridSize={gridSize}
        systems={systems}
        selectedCoords={selectedCoords}
        setSelectedCoords={handleCoordsChange}
        viewState={viewState}
        setViewState={setViewState}
        showLeftSidebar={showLeftSidebar}
        setShowLeftSidebar={setShowLeftSidebar}
        showRightSidebar={showRightSidebar}
        setShowRightSidebar={setShowRightSidebar}
      />

      {showRightSidebar && (
        <InspectorPanel
          gridSize={gridSize}
          systems={systems}
          selectedCoords={selectedCoords}
          setSelectedCoords={handleCoordsChange}
          focusedObject={focusedObject}
          setFocusedObject={setFocusedObject}
        />
      )}
    </div>
  );
}

